const fs = require('fs');

// Service enhancement templates by category
const templates = {
  hair: {
    purpose: (name) => `Designed for individuals experiencing ${name.toLowerCase().includes('exam') ? 'hair loss assessment and diagnosis' : name.toLowerCase().includes('peel') ? 'scalp detoxification and hair health improvement' : 'hair restoration and scalp health optimization'}. Ideal for those seeking professional hair care solutions.`,
    procedure: (name) => `This specialized hair treatment involves ${name.toLowerCase().includes('exam') ? 'comprehensive scalp analysis using advanced diagnostic tools' : name.toLowerCase().includes('peel') ? 'medical-grade exfoliation of the scalp to remove buildup and promote healthy hair growth' : 'targeted application of restorative compounds to nourish hair follicles and improve scalp condition'}.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('exam') ? 'Comprehensive scalp analysis using dermoscopy and other diagnostic tools to assess hair follicle health, identify underlying causes of hair loss, and create personalized treatment plans.' : name.toLowerCase().includes('peel') ? 'Medical-grade chemical exfoliation that removes dead skin cells, excess sebum, and product buildup from the scalp, creating an optimal environment for healthy hair growth.' : 'Delivers essential nutrients, growth factors, and therapeutic compounds directly to the hair follicle roots, stimulating cellular metabolism and promoting stronger, healthier hair growth.'}`
  },
  skin: {
    purpose: (name) => `Specifically formulated for individuals with ${name.toLowerCase().includes('scar') ? 'acne scars and skin imperfections' : name.toLowerCase().includes('infection') ? 'bacterial, fungal, or viral skin infections' : name.toLowerCase().includes('mole') ? 'unwanted moles and skin growths' : 'various skin conditions and imperfections'}. Provides targeted treatment with lasting results.`,
    procedure: (name) => `This advanced skin treatment utilizes ${name.toLowerCase().includes('surgery') ? 'precision surgical techniques' : name.toLowerCase().includes('laser') ? 'focused laser energy' : name.toLowerCase().includes('cautery') ? 'electrocautery methods' : 'specialized medical procedures'} to address the specific skin concern effectively and safely.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('surgery') ? 'Surgical removal of unwanted skin growths using sterile techniques, ensuring complete removal while minimizing scarring and preserving surrounding healthy tissue.' : name.toLowerCase().includes('laser') ? 'Precise laser energy targets specific skin concerns, breaking down unwanted tissue while protecting surrounding healthy skin.' : name.toLowerCase().includes('cautery') ? 'Controlled electrocautery destroys abnormal tissue through heat, promoting healing and preventing recurrence.' : 'Medical-grade treatment that addresses the root cause of skin conditions, promoting healing and preventing future occurrences.'}`
  },
  acne: {
    purpose: (name) => `Comprehensive solution for ${name.toLowerCase().includes('scar') ? 'acne scarring and post-acne marks' : name.toLowerCase().includes('facial') ? 'active acne and skin cleansing' : 'acne-related skin concerns and imperfections'}. Effective for all acne severities and skin types.`,
    procedure: (name) => `This specialized acne treatment combines ${name.toLowerCase().includes('peel') ? 'chemical exfoliation' : name.toLowerCase().includes('laser') ? 'laser resurfacing' : name.toLowerCase().includes('roller') ? 'microneedling techniques' : 'advanced therapeutic methods'} to target acne-causing factors and promote clear, healthy skin.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('peel') ? 'Medical-grade chemical exfoliation that penetrates pores to dissolve excess sebum, unclog follicles, and reduce bacterial colonization that causes acne breakouts.' : name.toLowerCase().includes('laser') ? 'Laser energy targets sebaceous glands and bacteria, reducing oil production and inflammation while stimulating collagen production for smoother skin.' : name.toLowerCase().includes('roller') ? 'Micro-needling creates controlled micro-injuries that stimulate collagen production and enhance product absorption for deeper acne treatment.' : 'Multi-modal approach that addresses hormonal, bacterial, and inflammatory factors contributing to acne formation and scarring.'}`
  },
  eyes: {
    purpose: (name) => `Specialized treatment for delicate under-eye concerns including ${name.toLowerCase().includes('circles') ? 'dark circles and pigmentation' : name.toLowerCase().includes('rejuvenation') ? 'aging signs and skin quality' : 'volume loss and fine lines'}. Safe for the sensitive eye area.`,
    procedure: (name) => `This gentle yet effective under-eye treatment uses ${name.toLowerCase().includes('removal') ? 'targeted lightening techniques' : name.toLowerCase().includes('rejuvenation') ? 'restorative compounds' : 'volumizing fillers'} specifically formulated for the delicate eye area to achieve natural-looking improvements.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('removal') ? 'Addresses multiple causes of dark circles including pigmentation, vascular issues, and volume loss through targeted treatments that brighten and restore the under-eye area.' : name.toLowerCase().includes('rejuvenation') ? 'Comprehensive eye area treatment combining hydration, collagen stimulation, and gentle resurfacing to reduce fine lines and improve skin quality.' : 'Hyaluronic acid fillers restore lost volume in the tear trough area, reducing shadows and creating a smoother transition between eyelid and cheek.'}`
  },
  pigmentation: {
    purpose: (name) => `Advanced solution for ${name.toLowerCase().includes('freckle') ? 'freckles and sun spots' : name.toLowerCase().includes('depigmentation') ? 'stubborn pigmentation' : name.toLowerCase().includes('glow') ? 'dull skin and brightness' : 'pigmentation concerns and skin tone'} issues. Effective for various pigmentation types and severities.`,
    procedure: (name) => `This comprehensive pigmentation treatment utilizes ${name.toLowerCase().includes('peel') ? 'medical-grade chemical formulations' : name.toLowerCase().includes('facial') ? 'multi-step hydradermabrasion' : name.toLowerCase().includes('dermapen') ? 'microneedling technology' : 'advanced therapeutic approaches'} to regulate melanin production and achieve even skin tone.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('peel') ? 'Controlled chemical exfoliation that inhibits melanin production while promoting cellular turnover for gradual skin lightening and tone improvement.' : name.toLowerCase().includes('facial') ? 'Multi-step hydradermabrasion that cleanses, exfoliates, extracts, and infuses brightening serums for comprehensive skin renewal.' : name.toLowerCase().includes('dermapen') ? 'Micro-needling creates pathways for targeted pigmentation treatments to penetrate deeper layers, addressing melanin at its source.' : 'Scientific approach that regulates tyrosinase activity and melanin production while protecting skin from UV damage and future pigmentation.'}`
  },
  medifacial: {
    purpose: (name) => `Professional medical facial treatment designed for ${name.toLowerCase().includes('diamond') ? 'gentle exfoliation' : name.toLowerCase().includes('oxy') ? 'oxygen infusion and skin renewal' : name.toLowerCase().includes('power') ? 'lifting and firming' : name.toLowerCase().includes('iv') ? 'systemic skin health' : 'comprehensive skin rejuvenation'}. Suitable for all skin types and concerns.`,
    procedure: (name) => `This advanced medical facial incorporates ${name.toLowerCase().includes('diamond') ? 'crystal-free microdermabrasion' : name.toLowerCase().includes('oxy') ? 'pressurized oxygen delivery' : name.toLowerCase().includes('power') ? 'muscle-stimulating peptides' : name.toLowerCase().includes('iv') ? 'intravenous nutrient infusion' : 'multiple therapeutic modalities'} for superior skin transformation and long-lasting results.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('diamond') ? 'Crystal-free exfoliation using diamond-encrusted tips to gently remove dead skin cells and stimulate collagen production without irritation.' : name.toLowerCase().includes('oxy') ? 'Supercharged oxygen delivery system that infuses nutrients and vitamins deep into skin tissues for enhanced cellular metabolism and renewal.' : name.toLowerCase().includes('power') ? 'Advanced peptide complex that stimulates facial muscles and skin tissue for natural lifting and contouring effects.' : name.toLowerCase().includes('iv') ? 'Intravenous delivery of vitamins, minerals, and antioxidants that nourish skin from within, promoting systemic skin health and radiance.' : 'Multi-step therapeutic process that combines cleansing, exfoliation, extraction, infusion, and protection for comprehensive skin transformation.'}`
  },
  antiaging: {
    purpose: (name) => `Advanced anti-aging treatment targeting ${name.toLowerCase().includes('peel') ? 'skin renewal and collagen stimulation' : name.toLowerCase().includes('collagen') ? 'skin elasticity and firmness' : 'skin tightening and rejuvenation'}. Effective for preventing and reversing signs of aging.`,
    procedure: (name) => `This comprehensive anti-aging treatment uses ${name.toLowerCase().includes('peel') ? 'medical-grade chemical exfoliation' : name.toLowerCase().includes('collagen') ? 'bioactive collagen precursors' : 'advanced skin tightening technology'} to restore youthful skin quality and appearance.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('peel') ? 'Controlled chemical exfoliation that removes damaged skin layers while stimulating collagen and elastin production for firmer, smoother skin.' : name.toLowerCase().includes('collagen') ? 'Delivers collagen-building peptides and nutrients that restore skin structure and elasticity from within.' : 'Utilizes thermal energy to contract collagen fibers and stimulate new collagen production for progressive skin tightening.'}`
  },
  laser: {
    purpose: (name) => `Precision laser treatment for ${name.toLowerCase().includes('hair') ? 'permanent hair reduction' : name.toLowerCase().includes('tattoo') ? 'tattoo removal' : name.toLowerCase().includes('mole') ? 'skin growth removal' : name.toLowerCase().includes('wart') ? 'wart elimination' : name.toLowerCase().includes('birthmark') ? 'vascular lesion treatment' : 'various skin concerns'}. Safe and effective for targeted conditions.`,
    procedure: (name) => `This advanced laser treatment employs ${name.toLowerCase().includes('hair') ? 'selective photothermolysis for follicle destruction' : name.toLowerCase().includes('tattoo') ? 'Q-switched technology for ink fragmentation' : 'focused light energy for precise tissue targeting'}, ensuring optimal results with minimal discomfort.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('hair') ? 'Laser energy is absorbed by melanin in hair follicles, converting to heat that damages follicle structure and prevents regrowth.' : name.toLowerCase().includes('tattoo') ? 'High-energy light pulses break down tattoo ink particles into smaller fragments that the body can naturally eliminate.' : 'Precise wavelength targeting allows selective destruction of unwanted tissue while preserving surrounding healthy skin.'}`
  },
  body: {
    purpose: (name) => `Specialized body treatment for ${name.toLowerCase().includes('weight') ? 'medical weight management' : name.toLowerCase().includes('cellulite') ? 'cellulite reduction and skin texture' : name.toLowerCase().includes('cryolipolysis') ? 'stubborn fat reduction' : name.toLowerCase().includes('shaping') ? 'body contouring and shaping' : 'fat reduction and body sculpting'}. Non-surgical approach to body transformation.`,
    procedure: (name) => `This comprehensive body treatment utilizes ${name.toLowerCase().includes('weight') ? 'medical weight management protocols' : name.toLowerCase().includes('cellulite') ? 'combination therapies for cellulite' : name.toLowerCase().includes('cryolipolysis') ? 'controlled cooling technology' : 'advanced body contouring methods'} to achieve natural-looking body improvements.`,
    whatItDoes: (name) => `${name.toLowerCase().includes('weight') ? 'Medical approach combining hormonal balancing, metabolism optimization, and lifestyle modification for sustainable weight management.' : name.toLowerCase().includes('cellulite') ? 'Multi-modal treatment addressing fat herniation, fibrous bands, and skin quality for comprehensive cellulite reduction.' : name.toLowerCase().includes('cryolipolysis') ? 'Controlled cooling induces fat cell apoptosis, allowing natural elimination while preserving surrounding tissues.' : 'Combination of fat reduction, skin tightening, and contouring technologies for comprehensive body transformation.'}`
  }
};

// Function to get category from service ID
function getCategory(serviceId) {
  if (serviceId.includes('hair') || serviceId.includes('scalp')) return 'hair';
  if (serviceId.includes('acne') || serviceId.includes('scar') || serviceId.includes('carbon') || serviceId.includes('fractional') || serviceId.includes('radiofrequency') || serviceId.includes('derma-roller')) return 'acne';
  if (serviceId.includes('eye') || serviceId.includes('circle') || serviceId.includes('under-eye')) return 'eyes';
  if (serviceId.includes('pigmentation') || serviceId.includes('freckle') || serviceId.includes('depigmentation') || serviceId.includes('cosmelan') || serviceId.includes('glow') || serviceId.includes('dermapen') || serviceId.includes('skin-booster') || serviceId.includes('hydrafacial')) return 'pigmentation';
  if (serviceId.includes('facial') || serviceId.includes('diamond') || serviceId.includes('oxy') || serviceId.includes('instabright') || serviceId.includes('power') || serviceId.includes('iv-infusion')) return 'medifacial';
  if (serviceId.includes('aging') || serviceId.includes('wrinkle') || serviceId.includes('collagen') || serviceId.includes('tightening')) return 'antiaging';
  if (serviceId.includes('laser') || serviceId.includes('birthmark') || serviceId.includes('tattoo') || serviceId.includes('wart') || serviceId.includes('mole') && !serviceId.includes('skin-tag')) return 'laser';
  if (serviceId.includes('weight') || serviceId.includes('cellulite') || serviceId.includes('cryolipolysis') || serviceId.includes('body') || serviceId.includes('fat')) return 'body';
  return 'skin'; // default
}

console.log('Enhancement templates ready for all categories');
